name: Update mst_category and mst_sub_category JSON

on:
  schedule:
    - cron: '*/5 * * * *'
  

jobs:
  update-json:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Ensure the GITHUB_TOKEN has write permissions to the repository

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install requests

    - name: Run the script
      run: |
        python update_mst_category.py
        python update_mst_subcategory.py

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add mst_category.json
        git add mst_subcategory.json
        git commit -m "Update mst_category data for $(date +'%Y-%m-%d')"
        git push https://github.com/${{ github.repository }}.git HEAD:main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
